### ISSUE TITLE
The emulator don't recognize the JAR from God Of War Betrayal

### ISSUE THREAD

**Issue by hardBSDk** [dlunch/wie#238]
It show the "Error: Unknown file format" message.

**Comment by dlunch** [comment]
Hi, you should point to .jad file alongside with .jar for now. but I think it would be nice to use accept .jar also, i'll address it later. Thanks!

**Comment by hardBSDk** [comment]
@dlunch I don't have a `jad` file.

**Comment by dlunch** [comment]
Fixed it to accept `jar` file
